name: Self-Hosted Runner | CI/CD | stmikbdg-api
# fix 7

on:
  push:
    branches: [Master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run deployment script
        run: |
          cd /var/www/stmikbdg-api
          git pull origin Master
          composer install --no-interaction --prefer-dist --optimize-autoloader

          php artisan optimize
